### ISSUE TITLE
slick carousel: Last slide image is missing when 'infinite: true'

### ISSUE THREAD

**Issue by kegelm** [rpajo/webpack-foundation-boilerplate#4]
How can i initiate slick slider after all the images have been loaded into the DOM?
I opened a issue directly at the slick github, but nobody can help me with this problem: https://github.com/kenwheeler/slick/issues/3577

Slick infinite will work fine if it fires once all the images are in the dom and set option to 'infinite: false'.
But i want to have a infinite carousel. So i have to set 'infinite: true', but the last image dont shows up.

My project:
http://kunden.markus-kegel.de/kronenmetzgerei

index.js
https://gist.github.com/kegelm/9b086db40c0218e3e7ff880ce7dedb7e

webpack.config.prod.js:
https://gist.github.com/kegelm/f05263cbcee96799233b2128a9381705

**Comment by rpajo** [comment]
Hey.

Make sure everything is importing okay.  Try importing the slick files (base css, theme & js) in index.js. Note that you have to add the font extensions to the file-loader in the webpack config:
```javascript
{
   test: /\.(jpe?g|png|gif|svg|tga|gltf|babylon|mtl|pcb|pcd|prwm|obj|mat|mp3|ogg|eot|ttf|woff)$/i,
      use: [
         {
            loader: 'file-loader',
            options: {
            limit: 10000,
            name: "assets/[name].[ext]"
         },
      }
   ]
}
```

**Comment by kegelm** [comment]
The bug is in the slick.min.js
I changed it to slick.js and now it works perfectly.

**Comment by rpajo** [comment]
Oh I see. I was also using the unminified version. Glad it works now.
